name: Install dependencies
on:
  push:
    branches: [ patch-3 ]
jobs:
  install:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 16.x
        uses: actions/setup-node@v2
        with:
          node-version: 16.x
      - name: Run npm install
        run: npm install
